-- Story load: Autorretrato (Van Gogh, Orsay) (slug: autorretrato-van-gogh) — draft state, pending Patrick's OK to publish
-- Pattern: girasoles / la-habitacion loads (idempotent, accent-safe, docker cp + psql -f).
-- Deletes are scoped: per-artwork, plus ONE artist-level film row (see below) — never artist_id-wide,
-- which would destroy Lust for Life (noche-estrellada) and Vincent & Theo (girasoles) connections.
-- REPLACEMENT (Patrick's decision, 2026-10-04): the artist-level At Eternity's Gate connection
-- created by la-habitacion's load (bedroom-focused analysis) is deleted and replaced by the
-- autorretrato-focused analysis below — one row per film-artist pair keeps the future artist page
-- clean. The replaced text is preserved in git history and docs/stories/la-habitacion-de-arles.md.
-- story_status: created -> draft (a promotion; publish is a separate, explicit step).
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'autorretrato-van-gogh');
delete from film_connections where film_id = (select id from films where title = 'At Eternity''s Gate' and year = 2018) and artist_id = (select id from artists where slug = 'vincent-van-gogh');
delete from curiosities where artwork_id = (select id from artworks where slug = 'autorretrato-van-gogh');
delete from image_assets where artwork_id = (select id from artworks where slug = 'autorretrato-van-gogh');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'autorretrato-van-gogh');
update artworks set summary = 'El Autorretrato de Orsay es un óleo sobre lienzo (65 × 54 cm) que Vincent van Gogh pintó en septiembre de 1889 en el asilo de Saint-Paul-de-Mausole, en Saint-Rémy-de-Provence, apenas recuperado de la crisis de julio que lo había tenido seis semanas sin poner un pie fuera de su cuarto. Es uno de los dos autorretratos de aquel mes —el primero, comenzado el día que se levantó, lo muestra «flaco, pálido como un demonio» sobre fondo azul violeta oscuro (hoy en la National Gallery of Art de Washington); este, el segundo, es de tres cuartos sobre fondo claro— y probablemente el último que pintó en su vida. Se lo envió a su hermano Theo como parte de tranquilidad, se lo llevó a Auvers para enseñárselo al doctor Gachet —que quedó «absolutamente fanático»— y desde 1949 vive en París: los hijos del doctor lo donaron al Estado francés (RF 1949 17) y hoy preside el Musée d''Orsay.', why_it_matters = 'Importa porque aquí el autorretrato deja de ser género y se convierte en mensaje: pintado por falta de dinero para modelos, es la carta médica que Vincent le manda a Theo —«el retrato te dirá mejor que mi carta cómo estoy»— y a la vez el punto final de una serie de unas 32 telas en diez años de mirarse a la cara. Esa cabeza inmóvil rodeada de arabescos que ondulan —pelo, barba, fondo— condensa su teoría del color en un solo choque de complementarios: barba naranja contra turquesa. Y que el rostro más sereno y más atormentado del arte moderno sea el de un hombre que sólo quería decirle a su hermano que estaba mejor, es la mejor lección de lo que un retrato puede hacer sin decir palabra.', essay = NULL, palette = '["#9BC8C0", "#345E5A", "#2F5D8F", "#C1552E", "#E8CFA8"]', story_status = 'draft', updated_at = now() where slug = 'autorretrato-van-gogh';
insert into films (title, year, director) select 'Loving Vincent', 2017, 'Dorota Kobiela y Hugh Welchman' where not exists (select 1 from films where title = 'Loving Vincent' and year = 2017 and director = 'Dorota Kobiela y Hugh Welchman');
insert into films (title, year, director) select 'At Eternity''s Gate', 2018, 'Julian Schnabel' where not exists (select 1 from films where title = 'At Eternity''s Gate' and year = 2018 and director = 'Julian Schnabel');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, (select id from artworks where slug = 'autorretrato-van-gogh'), null, null, 'El autorretrato como motor narrativo: la película entera es un retrato que investiga a un retratista', 'Primer largometraje de la historia pintado fotograma a fotograma al óleo: 65.000 cuadros ejecutados por 125 pintores (seleccionados de unos 5.000 aspirantes de más de 20 países) con la técnica de Vincent; como los artistas repintaban sobre el mismo lienzo tras cada toma, sólo sobrevivieron 1.000 de las 65.000 pinturas. Los actores se filmaron en verde, sus imágenes se compusieron sobre los cuadros y luego cada fotograma se pintó a mano; Robert Gulaczyk, el Vincent, se materializa en frontal como los autorretratos.', 'El film tiende a encuadrar a Vincent en frontal cerrado, reservando alrededor de la cabeza el mismo papel que el lienzo de 1889 le da al fondo: arabescos que ondulan mientras el rostro permanece inmóvil. En las transiciones la cámara deriva sobre la superficie pictórica como si recorriera el impasto, y la barba roja contra el turquesa funciona como eje cromático exacto que en el original: el complementario que sostiene la mirada. El retrato que Vincent pintó para decir «así estoy» se convierte aquí en la pregunta que recorre todo el film —¿quién era este hombre?— y la película responde mirándolo de frente, una y otra vez, a 24 cuadros por segundo.', 'none', NULL from films f where f.title = 'Loving Vincent' and f.year = 2017 and f.director = 'Dorota Kobiela y Hugh Welchman';
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, null, (select id from artists where slug = 'vincent-van-gogh'), null, 'La cara como acumulación de marcas — la interpretación como pintura', 'Schnabel dirigió a Willem Dafoe (Volpi Cup en Venecia, nominado al Óscar) desde la práctica de pintor: «sujeta el pincel como una espada», «no existe la mala pincelada». Dafoe aprendió a pintar y leyó las cartas para el papel, y definió el resultado así: «todo se junta en un remolino — un remolino de color, un remolino de luz. No es representación naturalista. Pero captura el espíritu».', 'El Vincent de Dafoe se nos da casi siempre a distancia de retrato: encuadres cerrados, cámara en mano que tiembla como tiemblan las pinceladas del fondo de Orsay, la cara del actor ocupando la proporción que la cabeza ocupa en el lienzo —alta, aplastada contra el borde superior, mirándonos. Donde Loving Vincent copia la técnica, Schnabel copia el método: no busca el parecido fotográfico sino la semejanza acumulada, marca sobre marca; la luz dura le roba los medios tonos y deja el rostro hecho de contrastes puros, naranja contra verde azulado. Es la lectura más honrada del autorretrato: no pintar cómo se veía, sino cómo se sentía mirado.', 'none', NULL from films f where f.title = 'At Eternity''s Gate' and f.year = 2018 and f.director = 'Julian Schnabel';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'autorretrato-van-gogh'), 1, 'Se dice que esta cara es la de un loco pintando su locura: la mirada fija de alguien al borde del colapso. Falso, y la carta lo desmiente: Vincent lo pintó en septiembre de 1889, ya recuperado de la crisis de julio, y lo concibió como un parte de convalecencia para calmar a Theo. «Estoy incluso inclinado a creer que el retrato te dirá mejor que mi carta cómo estoy, y que te tranquilizará — me ha costado bastante», le escribió. Y remató: junto a sus autorretratos de París, «ahora parezco más sano que entonces». La intensidad no es delirio: es un informe.', 'myth', 'https://vangoghletters.org/vg/letters/let800/letter.html', 'Carta 800 a Theo (5–6 sept 1889); la nota 5 de la edición identifica este lienzo (F 627 / JH 1772, Orsay)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'autorretrato-van-gogh'), 2, 'El modelo más barato que encontró: él mismo. En diez años pintó unos 32 autorretratos, en gran parte porque a menudo no tenía dinero para pagar modelos. En septiembre de 1889 trabajó en dos a la vez: el primero lo comenzó «el primer día que me levanté» —«flaco, pálido como un demonio», fondo azul violeta oscuro, hoy en Washington— y después este, «tres cuartos sobre fondo claro», el preferido y el enviado a Theo.', 'fact', 'https://en.wikipedia.org/wiki/Self-portrait_(van_Gogh,_Paris)', 'Wikipedia (cita Van Gogh Museum y Walther 2000); el detalle de los dos lienzos seguidos, en carta 800 (chip de la curiosidad 1)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'autorretrato-van-gogh'), 3, 'Probablemente el último. Los historiadores se dividen sobre si este lienzo o el autorretrato sin barba (colección privada) fue el definitivo: Walther y Hulsker sostienen que este; Pickvance defiende el otro. Lo cierto es que Vincent no volvió a pintarse al óleo en los diez meses que le quedaban: de los ~32 autorretratos de su vida, este es el punto final más aceptado.', 'fact', 'https://en.wikipedia.org/wiki/Self-portrait_(van_Gogh,_Paris)', 'Walther 2000 y Pickvance 1986, citados ahí');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'autorretrato-van-gogh'), 4, 'Al doctor le encantó — y su familia acabó custodiando la cara del paciente. Vincent se llevó el cuadro a Auvers-sur-Oise y se lo enseñó al doctor Gachet, que según él quedó «absolutamente fanático». Sesenta años después, en 1949, los hijos del doctor, Paul y Marguerite Gachet, lo donaron al Estado francés: el autorretrato entró en las colecciones nacionales con el número RF 1949 17 y hoy preside el Musée d''Orsay.', 'fact', 'https://en.wikipedia.org/wiki/Self-portrait_(van_Gogh,_Paris)', '«Fanático» vía Walther 2000/Denvir 1994 (citados en Wikipedia); la donación Gachet 1949 verificada además en la ficha estructurada del escán de Commons');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'autorretrato-van-gogh'), 5, 'Se cuenta que el fondo es un mapa de su mente. La lectura romántica —popularizada por críticas como Sister Wendy Beckett— ve en los colores que se disuelven y los patrones turbulentos la presión mental, física y emocional del artista; la propia ficha del Orsay alimenta la leyenda al oponer «la inmovilidad del modelo» a «las arabescas alucinatorias del fondo». ¿Diagnóstico o leyenda? Nadie puede verificar lo que un fondo «significa» — pero como retrato de un estado, pocos fondos dicen más.', 'legend', 'https://en.wikipedia.org/wiki/Self-portrait_(van_Gogh,_Paris)', 'Beckett 1994 y la ficha del Orsay (archivada), citadas ahí');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'autorretrato-van-gogh'), 'display', 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg', 'Google Art Project — Wikimedia Commons (dominio público)');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'autorretrato-van-gogh'), 'Segundo de los dos autorretratos de septiembre de 1889 (F 627 / JH 1772); donación de Paul y Marguerite Gachet al Estado francés, 1949 (RF 1949 17)', 'Musée d''Orsay', 'París', 'Francia');
commit;
-- end of story load: autorretrato-van-gogh (draft)
