-- Story load: Canasta de frutas (Caravaggio, Ambrosiana) (slug: canasta-de-frutas) — draft state, pending Patrick's OK to publish
-- Pattern: autorretrato / girasoles loads (idempotent, accent-safe, docker cp + psql -f).
-- Deletes scoped per-artwork. ZERO film_connections by design: the Jarman × Caravaggio artist-level
-- row is owned by la-vocacion-de-san-mateo.sql (one row per film-artist pair); no obra-level
-- connection verifies honestly for this canvas. Do NOT add one here without re-verification.
-- Dating: disputed 1596–1601 (seed says c. 1596; Ambrosiana ficha says after 1597) — told honestly in the copy.
-- story_status: created -> draft (a promotion; publish is a separate, explicit step).
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'canasta-de-frutas');
delete from curiosities where artwork_id = (select id from artworks where slug = 'canasta-de-frutas');
delete from image_assets where artwork_id = (select id from artworks where slug = 'canasta-de-frutas');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'canasta-de-frutas');
update artworks set summary = 'La canasta de frutas (Canestra di frutta) es un óleo sobre lienzo de 47 × 61 cm —así lo mide el museo— pintado en Roma hacia 1596, en el círculo del cardenal Del Monte: la datación exacta se disputa año a año (Spike propone 1596, Puglisi 1601, y la Ambrosiana sitúa la obra después de 1597). Sobre un fondo neutro que el inventario de 1607 llamaba todavía «campo blanco», una cesta de mimbre cargada de fruta de verano se asoma al borde de una repisa, a punto de caer en el espacio del espectador. Cuelga en la sala 1 de la Pinacoteca de la Veneranda Biblioteca Ambrosiana de Milán (inv. 151), donada en 1618 por el cardenal Federico Borromeo —su primer dueño documentado— junto al núcleo fundacional de la colección. El gancho: nada en esta cesta está sano. Cada fruto agusanado y cada hoja seca convierten el bodegón en un reloj de arena.', why_it_matters = 'Importa porque aquí la fruta asciende a protagonista absoluta: el propio museo lo llama «una suerte de prototipo del género que llegaría a llamarse naturaleza muerta», el único bodegón independiente de Caravaggio que ha llegado hasta nosotros. El pintor más célebre de Roma puso su ojo implacable —el mismo de sus santos y sus verdugos— al servicio de lo más humilde, sin retocar la verdad: manzana bichada, brevas reventando, hojas que se secan. Cuatro siglos de naturaleza muerta —del género popular que nace con él hasta Chardin, Cézanne y Morandi— arrancan en esta repisa.', essay = NULL, palette = '["#D8C49A", "#8A6234", "#9E3B22", "#5C6B35", "#2E2119"]', story_status = 'draft', updated_at = now() where slug = 'canasta-de-frutas';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'canasta-de-frutas'), 1, 'El mito: una «bagatela», un ejercicio menor de género. La teoría del tiempo ponía la naturaleza muerta casi al fondo de la escala: su amigo y coleccionista el marqués Vincenzo Giustiniani la colocó en el quinto puesto de doce en su tratado, entre las flores y «otras menudencias». El destape: el propio Caravaggio le espetó que «es tan difícil pintar un jarrón de flores como un cuadro con figuras humanas», y a partir de él el bodegón empieza a convertirse en género popular de la pintura italiana. El ejercicio menor resultó ser el acta de fundación.', 'myth', 'https://es.wikipedia.org/wiki/Cesto_con_frutas', 'Wikipedia ES (cita el tratado de Giustiniani vía Andreas Prater, Taschen; y la popularización del género a partir de Caravaggio)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'canasta-de-frutas'), 2, 'Toda la fruta está enferma, y hay un diagnóstico por especie. Un horticultor de la Universidad de Purdue (Jules Janick) catalogó los daños cuadro a cuadro: la manzana bicolor con dos entradas de carpocapsa y podredumbre en el borde; la hoja de la higuera con antracnosis; el racimo rojo con uvas ya momificadas; una hoja de parra deshidratada del todo; brotes roídos como por saltamontes. No es fruta genérica: son especímenes únicos, «fruta de retrato» comprada en el mercado y conservada para siempre. Y solo una pieza queda intacta: el membrillo.', 'fact', 'http://www.hort.purdue.edu/newcrop/caravaggio/caravaggio_l.html', 'J. Janick, «Caravaggio''s Fruit: A Mirror on Baroque Horticulture», Dept. of Horticulture, Purdue University (la fuente citada por las tres Wikipedias para el inventario patológico)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'canasta-de-frutas'), 3, 'Su primer dueño la describió de su puño y letra. El 17 de septiembre de 1607, el cardenal Federico Borromeo la anotaba en un codicilo: «un cuadro de un braccio de largo y tres cuartos de alto, donde sobre campo blanco está pintada una cesta de frutas… de mano de Michelangelo da Caravaggio». Borromeo, arzobispo de Milán y huésped de Del Monte en Roma, la adoraba: «Yo habría querido ponerle al lado otra cesta semejante, pero como nadie podía alcanzar la belleza y excelencia incomparable de esta, quedó sola». En 1618 la donó, con toda su colección, a la Ambrosiana que había fundado: de ahí no se ha movido.', 'fact', 'https://it.wikipedia.org/wiki/Canestra_di_frutta', 'Wikipedia IT (transcribe el codicillo de 1607 vía Marini y el elogio del Musaeum de Borromeo); la ficha del museo confirma la donación de 1618');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'canasta-de-frutas'), 4, 'Está pintada sobre una tela de segunda mano. Los rayos X muestran bajo la cesta los restos de una pintura anterior de grotescos —posiblemente de su amigo Prospero Orsi, apodado «Prosperino delle grottesche» justo por especializarse en eso—: la costumbre de un joven sin dinero que pintaba sobre stesure ajenas en la Roma de 1595. Y las mismas radiografías desmontaron un fantasma: contra lo que se creyó en la gran exposición de Milán de 1951, el cuadro no es el recorte de una composición mayor con figuras. Nació así, bodegón entero desde la primera pincelada.', 'fact', 'https://it.wikipedia.org/wiki/Canestra_di_frutta', 'Wikipedia IT (indagini radiografiche, Orsi, Longhi y la muestra de 1951)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'canasta-de-frutas'), 5, 'Se cuenta que la cesta es un memento mori: todo lo que madura, muere. Junto al fruto aún fresco convive el agusanado; las hojas se secan, se encogen y arrugan hasta lo irreversible —el propio museo lee en esa mezcla «el inexorable paso del tiempo», y admite lecturas religiosas del cuadro—. ¿Vanitas, sermón mudado a mimbre? ¿O simplemente la verdad del mercado romano, donde la fruta sin pesticidas llegaba así? El milagro es que las dos respuestas hagan el mismo cuadro.', 'legend', 'https://www.ambrosiana.it/en/discover/masterpieces/highlights/basket-of-fruit/', 'Ficha oficial de la Veneranda Biblioteca Ambrosiana («give tangible form to the inexorable passing of time»; interpretaciones religiosas)');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'canasta-de-frutas'), 'display', 'https://commons.wikimedia.org/wiki/File:Canestra_di_frutta_(Caravaggio).jpg', 'Reproducción de dominio público (PD-Art) — Wikimedia Commons · Pinacoteca Ambrosiana, Milán');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'canasta-de-frutas'), 'Pintado en Roma, círculo Del Monte. Datación disputada: c. 1596 (Spike, año del seed) – 1601 (Puglisi); la ficha del museo sitúa la obra después de 1597. Documentado en la colección de Federico Borromeo por codicillo de 17-IX-1607; donado a la Pinacoteca en 1618. Dimensiones según ficha del museo: 47 × 61 cm (en.wiki dice 46 × 64,5; it.wiki 47 × 62 — prevalece el museo).', 'Pinacoteca de la Veneranda Biblioteca Ambrosiana', 'Milán', 'Italia');
commit;
-- end of story load: canasta-de-frutas (draft)
