-- Story load: Chica con arete de perla (Vermeer, Mauritshuis) (slug: chica-con-arete-de-perla) — draft state, pending Patrick's OK to publish
-- Pattern: autorretrato / girasoles loads (idempotent, accent-safe, docker cp + psql -f).
-- Deletes scoped per-artwork. One obra-level connection (Girl with a Pearl Earring 2003); no artist-level rows owned here.
-- story_status: created -> draft (a promotion; publish is a separate, explicit step).
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'chica-con-arete-de-perla');
delete from curiosities where artwork_id = (select id from artworks where slug = 'chica-con-arete-de-perla');
delete from image_assets where artwork_id = (select id from artworks where slug = 'chica-con-arete-de-perla');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'chica-con-arete-de-perla');
update artworks set summary = 'Chica con arete de perla (Meisje met de parel; en español también La joven de la perla) es un óleo sobre lienzo pequeño —44,5 × 39 cm— que Johannes Vermeer pintó en Delft hacia 1665. No es un retrato sino un tronie: una cabeza de estudio con atrezzo prestado «a la turca» —turbante azul ultramar, paño ocre, collar blanco— y una muchacha que gira el cuello hacia nosotros como sorprendida a mitad de un movimiento, los labios entreabiertos, una perla imposible prendida en la oreja. Firmada «IVMeer» arriba a la izquierda, sin fecha. Desde 1902 vive en el Mauritshuis de La Haya, legada por el coleccionista que la compró por casi nada en 1881. La llaman «la Mona Lisa del Norte»: le sobra lo que a Leonardo le faltaba explicar.', why_it_matters = 'Importa porque es el instante congelado más puro del arte holandés: una rotación de cuello, una boca entreabierta, dos toques de luz en la perla —y nada más— llevan 350 años devolviéndonos la mirada. Vermeer llevó al límite su gramática de la luz —una sola fuente, un fondo que se traga el mundo— y la convirtió en retrato sin serlo: no sabemos quién es, y ese vacío es el motor de su fama. Es, además, el cuadro que le enseñó a la cultura moderna —novela, cine, memes— cómo mirar a Vermeer: no como ventana, sino como mirada.', essay = NULL, palette = '["#1B1710", "#DDB68A", "#27486E", "#C89B4B", "#EAE5DB"]', story_status = 'draft', updated_at = now() where slug = 'chica-con-arete-de-perla';
insert into films (title, year, director) select 'Girl with a Pearl Earring', 2003, 'Peter Webber' where not exists (select 1 from films where title = 'Girl with a Pearl Earring' and year = 2003 and director = 'Peter Webber');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, (select id from artworks where slug = 'chica-con-arete-de-perla'), null, null, 'La luz única de ventana y la rotación del cuello — el cuadro entero como destino narrativo', 'Basada en la novela de Tracy Chevalier (1999); Scarlett Johansson (Griet), Colin Firth (Vermeer); fotografía de Eduardo Serra. El Mauritshuis cedió una fotografía de altísima resolución del cuadro real, rodada en rostrum para el desenlace; Serra trabajó con luz difusa y negativos distintos en las escenas del taller «obsesionado con reproducir el uso de la luz de Vermeer»; a Johansson le decoloraron las cejas para acercarla al rostro del lienzo. El film construye sus cien minutos como el antes y el después del instante que el lienzo congeló: la perforación del lóbulo como clímax, la perla como recompensa.', 'El film ilumina a Griet como ilumina el cuadro: una sola fuente suave desde la izquierda —la ventana del taller—, el rostro modelado en degradados, el fondo cayendo a un negro que devora la habitación. En los primeros planos, Johansson gira la cabeza sobre el hombro hacia esa luz exactamente como la muchacha del lienzo, y la cámara se queda quieta, en eje, respetando la frontalidad del tronie. Durante casi todo el metraje el color se raciona —grises, ocres lavados, la ropa parda de la criada— hasta que llega la sesión de posado y el film detona la paleta que venía ahorrando: azul ultramar en la tela de la cabeza, ocre en el paño, blanco en el collar. El pigmento se convierte en acontecimiento narrativo. Y el último plano lo firma: sobre la reproducción cedida por el Mauritshuis, la cámara retrocede desde el destello de la perla hasta el cuadro completo — la ficción se disuelve en la superficie pintada y Griet deviene la chica. Es la única película cuyo tercer acto es, literalmente, un cuadro.', 'none', NULL from films f where f.title = 'Girl with a Pearl Earring' and f.year = 2003 and f.director = 'Peter Webber';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'chica-con-arete-de-perla'), 1, '«La Mona Lisa del Norte» no es un retrato —y desde luego no es la hija de Vermeer. Durante décadas se ha repetido que la muchacha es María, la hija mayor del pintor. Mito destapado: el cuadro es un tronie, el género holandés del s. XVII para la «cabeza» de estudio —rostro con atrezzo prestado, turbante exótico, sin cliente ni encargo—. Puede que existiera o puede que sea un rostro compuesto; los historiadores descartan la teoría de la hija como un anacronismo. Su anonimato no es un descuido del archivo: es el diseño del cuadro.', 'myth', 'https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring', 'Wikipedia (en), secciones «Description» y «Painting title»: tronie, identidad en disputa, teoría de la hija desestimada como anacronismo');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'chica-con-arete-de-perla'), 2, 'Costó dos florines y treinta céntimos. En 1881, en una subasta en La Haya, Arnoldus Andries des Tombe se llevó el lienzo —en estado lastimoso, con la pintura desprendiéndose— por 2,30 florines con el premio del comprador incluido: unos 24 € de 2015. Le avisó Victor de Stuers, el hombre que llevaba años impidiendo que los pocos Vermeer del mercado salieran del país. Des Tombe murió sin herederos y en 1902 legó el cuadro al Mauritshuis, donde cuelga desde entonces. La ganga más célebre de la historia del arte.', 'fact', 'https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring', 'Wikipedia (en), «Ownership and display»; los datos estructurados de Commons (Q185372) confirman casa Venduehuis der Notarissen, 2,30 florines, restauración en 1882 y legado de 1902');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'chica-con-arete-de-perla'), 3, 'El fondo negro fue verde —y detrás había una cortina. En 2018 el Mauritshuis descolgó el cuadro y lo examinó dos semanas en un taller de cristal abierto al público (proyecto The Girl in the Spotlight). El «vacío» oscuro resultó ser una veladura verde translúcida —índigo y gualda sobre una capa de negro de carbón— que se ha ido apagando durante siglos, con pliegues de tela visibles a la derecha: quizá una cortina. Los escáneres incluso rescataron la firma, «IVMeer», arriba a la izquierda, casi invisible a simple vista. La chica no flota en la oscuridad: está en una habitación.', 'fact', 'https://www.nature.com/articles/s40494-019-0311-9', 'Vandivere et al., «Fading into the background», npj Heritage Science 7:69 (2019), acceso abierto — equipo de The Girl in the Spotlight; MA-XRF, OCT y microscopía 3D');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'chica-con-arete-de-perla'), 4, 'La perla quizá no sea perla. En 2014 el astrofísico Vincent Icke publicó un artículo de título demoledor: «Meisje met geen parel» —«La chica sin perla»—. Su argumento es óptico: el reflejo de la joya es demasiado nítido; una perla verdadera dispersa la luz, un metal pulido la devuelve especular. Y el tamaño, descomunal incluso para las perlas de época. Conclusión: más bien un disco de estaño. Los investigadores del museo añaden la suya: la perla no tiene contorno ni gancho del que colgar de la oreja. Un truco de dos pinceladas —y funciona desde hace tres siglos y medio.', 'fact', 'https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring', 'Wikipedia (en), «Description» y «Painting technique»; cita el artículo de Icke en Nederlands Tijdschrift voor Natuurkunde (dic. 2014) y el reproche de «sin contorno ni gancho»');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'chica-con-arete-de-perla'), 5, 'Se cuenta que era la hija mayor de Vermeer; se cuenta que Magdalena, la niña de doce años de su mecenas Van Ruijven —la teoría de Andrew Graham-Dixon—; se cuenta que una sibila o una figura bíblica; se cuenta que una sirvienta cualquiera de Delft. El inventario tras la muerte del pintor solo la llama, en 1675, parte de «dos tronies pintados a la turca», y la subasta de 1696 la describe sin nombre propio. El único nombre que ha tenido nunca se lo regaló una novelista: Griet, la criada que Tracy Chevalier inventó en 1999. La identidad más persuasiva de la chica es, por ahora, una ficción.', 'legend', 'https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring', 'Wikipedia (en), «Description», «Painting title» (inventario de 1675, subasta Dissius de 1696) y «Cultural impact» (Chevalier 1999, Griet)');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'chica-con-arete-de-perla'), 'display', 'https://commons.wikimedia.org/wiki/File:1665_Girl_with_a_Pearl_Earring.jpg', 'Mauritshuis — Wikimedia Commons (dominio público)');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'chica-con-arete-de-perla'), 'Tronie sin problema de versiones. Desde 2014 no viaja: tras décadas de giras mundiales, el Mauritshuis la mantiene en exposición permanente.', 'Mauritshuis', 'La Haya', 'Países Bajos');
commit;
-- end of story load: chica-con-arete-de-perla (draft)
