-- Story load: Girasoles (slug: girasoles) — draft state, pending Patrick's OK to publish
-- Pattern: noche-estrellada recovery load (idempotent, accent-safe, docker cp + psql -f).
-- Deletes are scoped: does NOT touch noche-estrellada connections (Lust for Life is
-- artist-level for the same artist — an artist_id-wide delete would destroy it).
-- story_status: created -> draft (a promotion; publish is a separate, explicit step).
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'girasoles');
delete from film_connections where film_id = (select id from films where title = 'Vincent & Theo' and year = 1990) and artist_id = (select id from artists where slug = 'vincent-van-gogh');
delete from curiosities where artwork_id = (select id from artworks where slug = 'girasoles');
delete from image_assets where artwork_id = (select id from artworks where slug = 'girasoles');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'girasoles');
update artworks set summary = 'Girasoles (Naturaleza muerta: jarrón con quince girasoles) es un óleo sobre lienzo (92,1 × 73 cm) que Vincent van Gogh pintó en agosto de 1888 en la Casa Amarilla de Arles, dentro de una semana de trabajo febril. Es la cuarta versión de la serie: Vincent la colgó en la habitación que preparaba para Paul Gauguin, cuya llegada esperaba como el primer paso de su «Taller del Sur». Firmada solo «Vincent» —en azul, sobre el jarrón—, es un cuadro amarillo sobre amarillo: fondo trigo pálido, mesa ocre, pétalos cromo, y una sola línea azul para separar los dos amarillos. Desde 1924 vive en la National Gallery de Londres, comprada con el fondo Courtauld (NG3863).', why_it_matters = 'Importa porque aquí una flor «vulgar» se convierte en firma personal: «yo tengo el girasol, en cierto modo», escribió Vincent, y ningún otro pintor ha quedado tan indisolublemente unido a una flor. El amarillo sobre amarillo —un solo color primario llevado al límite— es el nacimiento de su estilo maduro de Arles y una declaración de hospitalidad: eran la bienvenida pintada para Gauguin, amistad y gratitud convertidas en pigmento. Y su práctica de versiones y réplicas convierte un ramo en serie, un gesto profundamente moderno.', essay = NULL, palette = '["#E9D26A", "#C9971E", "#F2C230", "#7A4E1A", "#3D5A80"]', story_status = 'draft', updated_at = now() where slug = 'girasoles';
insert into films (title, year, director) select 'Vincent & Theo', 1990, 'Robert Altman' where not exists (select 1 from films where title = 'Vincent & Theo' and year = 1990 and director = 'Robert Altman');
insert into films (title, year, director) select 'Loving Vincent', 2017, 'Dorota Kobiela y Hugh Welchman' where not exists (select 1 from films where title = 'Loving Vincent' and year = 2017 and director = 'Dorota Kobiela y Hugh Welchman');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, (select id from artworks where slug = 'girasoles'), null, null, 'El girasol como identidad y la pincelada punteada como textura narrativa', 'Primer largometraje de la historia pintado fotograma a fotograma al óleo (65.000 cuadros, 125 pintores). En las secuencias de Arles los girasoles aparecen como el emblema doméstico de Vincent —el cuadro que Gauguin quería—, y el film entero hereda su gramática: el amarillo cromo y el empaste sembrado punto a punto.', 'Donde La noche estrellada prestaba a Loving Vincent su geometría de remolinos, los girasoles le prestan la superficie: cabezas florales construidas con trazos cortos de empaste, casi un puntillismo de pasta, que la película imita cuando sus retratos «se pintan» ante la cámara. El amarillo invade los interiores de la Casa Amarilla como estado emocional —hospitalidad, después ausencia—, y el jarrón azul-firmado funciona como firma dentro de la firma: el cuadro aparece siempre de cuerpo entero, frontal, en el eje del espectador, igual que colgaba en la habitación de Gauguin. Es el único «personaje» del film que no envejece.', 'none', NULL from films f where f.title = 'Loving Vincent' and f.year = 2017 and f.director = 'Dorota Kobiela y Hugh Welchman';
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, null, (select id from artists where slug = 'vincent-van-gogh'), null, 'El precio tardío del girasol: la puja de 1987 como prólogo de la pobreza de Vincent', 'Altman enmarca la vida de los hermanos con el martillo de Christie''s —un girasol vendido por 39,9 M$ en 1987, récord absoluto entonces— contra Vincent contando francos para los lienzos. El film insiste en la materialidad del oficio: tubos, marcos, tela sin preparar.', 'La elipsis que estructura el film es pura carta 741: Vincent escribió «mis girasoles valen 500 francos» sabiendo que nadie se los pagaba; Altman simplemente corta de esa frase implícita al martillo de un siglo después. La cámara trata los cuadros como mercancía salvaje —empaquetados, clavados, subastados— y solo en las escenas de trabajo los deja respirar en plano fijo, como si el único lugar donde un girasol vale lo que Vincent decía es el caballete.', 'none', NULL from films f where f.title = 'Vincent & Theo' and f.year = 1990 and f.director = 'Robert Altman';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'girasoles'), 1, 'La imagen más famosa de Vincent pintando girasoles es mentira. Es el retrato que Gauguin hizo de él —Van Gogh pintando girasoles, diciembre de 1888, Museo Van Gogh—, pero la escena nunca ocurrió: la temporada de los girasoles ya había acabado y Vincent no tocó el tema en absoluto durante los dos meses que Gauguin vivió en Arles. Gauguin pintó a Vincent como quería recordarlo: en posesión de su flor.', 'myth', 'https://www.nationalgallery.org.uk/paintings/vincent-van-gogh-sunflowers', 'National Gallery, ficha de la obra («The scene was imagined»)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'girasoles'), 2, 'Pintó las cuatro primeras versiones en una sola semana, contra el reloj de la flor. «Pinto con el entusiasmo de un marsellés comiendo bullabesa», le escribió a Theo, y trabajaba cada mañana desde el amanecer «porque las flores se marchitan rápido y hay que hacerlo todo de una vez». Su plan: una docena de paneles, «una sinfonía en azul y amarillo», para decorar el taller que soñaba compartir con Gauguin.', 'fact', 'https://vangoghletters.org/vg/letters/let666/letter.html', 'Carta 666 a Theo (21–22 agosto 1888); describe los tres lienzos en marcha: el tercero, «claro sobre claro, y será el mejor» — el antepasado directo de esta versión');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'girasoles'), 3, 'Son siete cuadros, y uno murió en la guerra. Cuatro versiones en agosto de 1888 y tres réplicas en enero de 1889 («copias absolutamente iguales e idénticas», según Vincent). Cinco cuelgan hoy en museos —Londres, Ámsterdam, Múnich, Filadelfia, Tokio—, una está en una colección privada, y la segunda versión, fondo azul real, fue destruida en 1945 por un bombardeo estadounidense en Ashiya, Japón.', 'fact', 'https://www.nationalgallery.org.uk/paintings/vincent-van-gogh-sunflowers', 'National Gallery, ficha de la obra');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'girasoles'), 4, '«Jeannin tiene la peonía, Quost tiene la malva real… pero yo tengo el girasol, en cierto modo.» Gauguin se había enamorado justo de esta tela y pedía quedársela; Vincent, que le debía mucho, le ofreció repetirle una «copia idéntica» —así nacieron las réplicas de enero—, pero al final se quedó su girasol: hoy es el de Londres. Y apuntó su precio sin pudor: 500 francos, «para fundir esos oros hace falta toda la energía de uno».', 'fact', 'https://vangoghletters.org/vg/letters/let741/letter.html', 'Carta 741 a Theo (22 enero 1889); la nota 11 del proyecto de cartas confirma que el codiciado era F454, este lienzo');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'girasoles'), 5, 'Quince girasoles, quince edades: un botón que no abre, siete en plena flor, siete ya pasadas a semilla. La tradición holandesa del s. XVII leía en las flores cortadas una vanitas —todo lo vivo se marchita—, y Vincent añadió su propio símbolo: en 1890 le sugirió al crítico Aurier que sus dos girasoles expuestos en Bruselas podían «expresar la idea que simboliza la gratitud». Un ramo que agradece, duele y espera a la vez.', 'legend', 'https://www.nationalgallery.org.uk/paintings/vincent-van-gogh-sunflowers', 'National Gallery, ficha de la obra (recuento botánico: 1 + 7 + 7)');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'girasoles'), 'display', 'https://commons.wikimedia.org/wiki/File:Vincent_Willem_van_Gogh_127.jpg', 'National Gallery (zoomable image) — Wikimedia Commons (dominio público)');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'girasoles'), 'Cuarta versión (agosto 1888). En préstamo al Philadelphia Museum of Art, exposición «Van Gogh''s Sunflowers: A Symphony in Blue and Yellow», 6 jun – 11 oct 2026.', 'National Gallery', 'Londres', 'Reino Unido');
commit;
-- end of story load: girasoles (draft)
