-- Story load: La habitación en Arles (slug: la-habitacion-de-arles) — draft, then publish with Patrick's OK (given 2026-10-03)
-- Pattern: girasoles load (idempotent, accent-safe, docker cp + psql -f).
-- Deletes scoped per-artwork + per-film; an artist_id-wide delete would destroy Lust for Life
-- (noche-estrellada) and Vincent & Theo (girasoles) artist-level connections.
-- Curiosity 5 (discoloration legend) loaded with Patrick's explicit approval of the VGM-video chip.
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'la-habitacion-de-arles');
delete from film_connections where film_id = (select id from films where title = 'At Eternity''s Gate' and year = 2018) and artist_id = (select id from artists where slug = 'vincent-van-gogh');
delete from curiosities where artwork_id = (select id from artworks where slug = 'la-habitacion-de-arles');
delete from image_assets where artwork_id = (select id from artworks where slug = 'la-habitacion-de-arles');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'la-habitacion-de-arles');
update artworks set summary = 'La habitación en Arles (título propio de Vincent: simplemente La habitación / La chambre à coucher) es un óleo sobre lienzo (72 × 90 cm) que Vincent van Gogh pintó a mediados de octubre de 1888 en la Casa Amarilla de Arles, el 2 de Place Lamartine: su dormitorio, con la puerta izquierda dando a la habitación que mantenía preparada para Gauguin. Son tres las versiones auténticas descritas en sus cartas — Ámsterdam (oct 1888, F482), Chicago (sept 1889, F484) y París-Orsay (sept 1889, F483, réduction para su madre y su hermana Wil) — y se distinguen entre sí, precisamente, por los cuadros colgados en la pared del fondo. La primera versión vive desde 1962 en el Van Gogh Museum de Ámsterdam, en préstamo permanente de la Fundación Vincent van Gogh.', why_it_matters = 'Importa porque aquí el tema del cuadro es, literalmente, el descanso: «mirar la pintura debe descansar la mente», escribió Vincent, que acababa de pasarse días en cama por agotamiento y pintó su habitación «para tomarse la revancha de aquel descanso forzado». Es un retrato de sí mismo sin cuerpo — el artista ausente, presente solo en sus dos sillas, su toalla y su chaqueta colgada — y a la vez un manifiesto de color plano a la manera de los grabados japoneses, sin sombras. Y como la Casa Amarilla fue bombardeada en 1944 y derribada, el cuadro es hoy el único lugar donde esa habitación sigue existiendo.', essay = NULL, palette = '["#9FB4C7", "#E3C05C", "#B33A2B", "#4C7A5D", "#D98E3B"]', story_status = 'draft', updated_at = now() where slug = 'la-habitacion-de-arles';
insert into films (title, year, director) select 'At Eternity''s Gate', 2018, 'Julian Schnabel' where not exists (select 1 from films where title = 'At Eternity''s Gate' and year = 2018 and director = 'Julian Schnabel');
insert into films (title, year, director) select 'Loving Vincent', 2017, 'Dorota Kobiela y Hugh Welchman' where not exists (select 1 from films where title = 'Loving Vincent' and year = 2017 and director = 'Dorota Kobiela y Hugh Welchman');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, (select id from artworks where slug = 'la-habitacion-de-arles'), null, null, 'La habitación como escenario del ausente: el cuarto reconstruido en tres dimensiones que la cámara habita', 'El film pintado al óleo recrea los interiores de Arles —la Casa Amarilla, el dormitorio— como espacios transitables, y usa los cuadros como decorado vivo: los mismos amarillos, la misma silla, la misma ventana. Donde Vincent aplanó el espacio a lo japonés, la película lo profundiza y lo hace caminable, conservando su paleta exacta.', 'La habitación de Loving Vincent funciona como el «plano establishing» emocional del Arles recordado: cada vez que la memoria vuelve a la Casa Amarilla, la composición retoma el punto de vista del cuadro —cama a la izquierda, sillas enfrentadas, ventana al fondo— y luego lo abandona en travelling, como quien sale de un cuadro que de pronto tiene profundidad. Es la inversa exacta del procedimiento de Vincent: él quitó sombras y perspectiva para descansar la vista; el film las devuelve para que el ojo busque al pintor que ya no está. El cuarto se convierte en el retrato que la película no muestra: Vincent ausente, sus sillas todavía hablándose.', 'none', NULL from films f where f.title = 'Loving Vincent' and f.year = 2017 and f.director = 'Dorota Kobiela y Hugh Welchman';
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, null, (select id from artists where slug = 'vincent-van-gogh'), null, 'El cuerpo del pintor dentro del cuarto: la habitación no como decorado sino como el lugar donde se vive y se colapsa', 'Schnabel —pintor él mismo— rodó en localizaciones reales de Arles y Saint-Rémy con cámara en mano y focos desenfocados; los interiores domésticos de Vincent aparecen con la materialidad del taller: lienzo, tubo, cama. Dafoe construye un Vincent físico, que se tumba y se levanta de esa cama.', 'Donde el cuadro es un retrato sin cuerpo, el film de Schnabel es todo cuerpo: cámara nerviosa pegada al hombro de Dafoe, respiración, peso. La habitación deja de ser composición y vuelve a ser cuarto real — camas que crujen, luz de Provenza por la ventana verde. Es la lectura complementaria de la carta 705: Vincent quiso pintar «descanso absoluto» porque no lo tenía; Schnabel filma precisamente esa falta, el reposo como algo que al personaje se le niega. El cuadro descansaba por él.', 'none', NULL from films f where f.title = 'At Eternity''s Gate' and f.year = 2018 and f.director = 'Julian Schnabel';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 1, 'Se suele contar que Vincent pintó su habitación ya encerrado, desde la enfermedad. Falso: la primera versión es del 16–17 de octubre de 1888, dos meses antes de la crisis de la oreja, pintada en la casa que acababa de amueblar y con los ojos aún cansados… de trabajar. El origen real del cuadro es una revancha: llevaba días en cama por agotamiento y decidió pintar el descanso mismo — «para tomarme la revancha de aquel descanso forzado que me obligaron a tomar».', 'myth', 'https://vangoghletters.org/vg/letters/let705/letter.html', 'Carta 705 a Theo, fechada «Arles, martes 16 octubre 1888» — la propia carta desmiente el mito; a Gauguin le contó los 2,5 días de reposo (carta 706)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 2, 'Es un cuadro con inventario de color incluido. «Las paredes son de violeta pálido. El suelo es de tejas rojas. La cama y las sillas, amarillo mantequilla fresco. Las sábanas y las almohadas, verde limón muy vivo. La colcha, rojo escarlata. La ventana verde. El tocador naranja, la jofaina azul. Las puertas lila.» Y sin sombras: «coloreado en tintas planas, como los grabados japoneses».', 'fact', 'https://vangoghletters.org/vg/letters/let705/letter.html', 'Carta 705 a Theo (16 octubre 1888); añadió un croquis que luego no coincide con el cuadro final — cambió el sombrero de lado y quitó la jofaina (nota 1 de la edición)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 3, 'La perspectiva «imposible» del cuarto es media verdad: la habitación de la Casa Amarilla no era rectangular sino trapezoidal — un ángulo obtuso en la esquina izquierda del frente y uno agudo en la derecha — según los planos del arquitecto arlesiano Léon Ramser que sobrevivieron al bombardeo de 1944. La otra mitad es decisión: suprimió las sombras y aplanó el espacio a lo japonés.', 'fact', 'https://en.wikipedia.org/wiki/Bedroom_in_Arles', 'Wikipedia, nota 1 (planos Ramser, citando a Roland Dorn, 1990)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 4, 'La versión original se mojó. En abril de 1889, con Vincent internado en el hospital de Arles, la crecida del Ródano dañó el cuadro enviado a Theo; Theo lo hizo reentelar y devolver, y Vincent lo copió en tamaño original — la «répétition» de Chicago, septiembre 1889 — y además pintó una réduction más pequeña para su madre y su hermana Wil, la de Orsay. Tres habitaciones, tres museos.', 'fact', 'https://en.wikipedia.org/wiki/Bedroom_in_Arles', 'Wikipedia, sección Second version (cartas 592, T10 y 604 del proyecto de cartas)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 5, 'El cuarto que vemos no es el que pintó: Vincent escribió «paredes violeta pálido», pero hoy se ven azuladas — la investigación del Van Gogh Museum sostiene que el pigmento rojo (laca de geranio) se ha desteñido con el tiempo, y en 2010–2011 el museo restauró el cuadro y reconstruyó digitalmente sus colores originales. El violeta existe solo en la carta y en el píxel.', 'legend', 'https://www.youtube.com/watch?v=pgOm9rjEtgI', 'Vídeo oficial del Van Gogh Museum «Discoloration of Van Gogh''s Bedroom» (10:20), enlazado desde Wikipedia; el violeta original está verificado en la carta 705 — aprobado por Patrick con bandera (2026-10-03)');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 'display', 'https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg', 'Google Arts & Culture — Wikimedia Commons (dominio público)');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 'Primera versión (octubre 1888, F482/JH1608); Fundación Vincent van Gogh, préstamo permanente desde 1962', 'Van Gogh Museum', 'Ámsterdam', 'Países Bajos');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 'Répétition a tamaño original (septiembre 1889, F484); Helen Birch Bartlett Memorial Collection desde 1926', 'Art Institute of Chicago', 'Chicago', 'Estados Unidos');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'la-habitacion-de-arles'), 'Réduction para su madre y su hermana Wil (finales de septiembre 1889, F483); colecciones nacionales francesas desde 1959', 'Musée d''Orsay', 'París', 'Francia');
commit;
-- end of story load: la-habitacion-de-arles (draft)
