-- Story load: La lechera (Vermeer, Rijksmuseum) (slug: la-lechera) — draft state, pending Patrick's OK to publish
-- Pattern: autorretrato / girasoles loads (idempotent, accent-safe, docker cp + psql -f).
-- Deletes are scoped per-artwork plus the one artist-level row this load owns (Tim's Vermeer × Vermeer).
-- Never artist_id-wide: that would destroy other artists' rows and other films' Vermeer rows.
-- story_status: created -> draft (a promotion; publish is a separate, explicit step).
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'la-lechera');
delete from film_connections where film_id = (select id from films where title = 'Tim''s Vermeer' and year = 2013) and artist_id = (select id from artists where slug = 'johannes-vermeer');
delete from curiosities where artwork_id = (select id from artworks where slug = 'la-lechera');
delete from image_assets where artwork_id = (select id from artworks where slug = 'la-lechera');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'la-lechera');
update artworks set summary = 'La lechera (Het melkmeisje) es un óleo sobre lienzo de pequeño formato (45,5 × 41 cm) que Johannes Vermeer pintó en Delft hacia 1658 —las dataciones bailan: el Met propone c. 1657–58 y la ficha vigente del Rijksmuseum firma c. 1660—. Una criada de cocina, de cofia blanca y delantal azul, vierte leche de una jarra de loza a una olla de barro junto a un pan; en la habitación encalada todo está quieto salvo el hilo de leche. Desde 1908 vive en el Rijksmuseum de Ámsterdam —comprada a los herederos Six con apoyo de la Vereniging Rembrandt— y cuelga hoy en su Galería de Honor (SK-A-2344).', why_it_matters = 'Importa porque aquí el trabajo doméstico —verter leche, el acto más mundano del mundo— se convierte en monumento: figura piramidal, punto de vista bajo y una quietud que hace de una sirvienta una estatua. Es la puerta del Vermeer maduro —«su última obra temprana o su primera obra maestra», en palabras del conservador Walter Liedtke—: por primera vez la luz, repartida en puntos de color sobre el pan y la cesta, se comporta como el verdadero tema. Y es una lección de dignidad: donde la tradición holandesa pintaba criadas como chiste picante, Vermeer pintó concentración.', essay = NULL, palette = '["#E7DAC4", "#C8942A", "#2F4B6B", "#7A3B2E", "#5A6A3C"]', story_status = 'draft', updated_at = now() where slug = 'la-lechera';
insert into films (title, year, director) select 'Tim''s Vermeer', 2013, 'Teller' where not exists (select 1 from films where title = 'Tim''s Vermeer' and year = 2013 and director = 'Teller');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, null, (select id from artists where slug = 'johannes-vermeer'), null, 'La pregunta «fotográfica» de Vermeer — ¿pintó con lentes y espejos?', 'El inventor Tim Jenison, enganchado a la tesis de Hockney (Secret Knowledge) y Steadman (Vermeer''s Camera), reconstruye pieza a pieza la sala de La lección de música —siete meses de carpintería, lente pulida a mano, pigmentos del XVII— y pinta su copia con un espejito fijado a 45°: cuando el borde del espejo «desaparece», el color es exacto. Por el camino cree ver en Vermeer aberración cromática y profundidad de campo de lente — cosas que el ojo humano no produce.', 'El documental alterna dos gramáticas: planos anchos y cenitales del taller reconstruido —una maqueta de Vermeer tratada como placa de ingeniería, luz fría y uniforme que convierte la escena en un problema de laboratorio— y primerosísimos planos macro del espejito a 45°, donde conviven en un mismo encuadre el reflejo del objeto y la pasta del lienzo: la comparación de color convertida en suspense visual. El clímax monta la copia de Jenison y el original cara a cara, eje frontal y simétrico, como un antes/después de feria de la ciencia. Es la hipótesis óptica contada en presente de indicativo — exactamente el mito que la curiosidad 1 destapa: el film demuestra que la máquina puede funcionar, nunca que Vermeer la usara.', 'none', NULL from films f where f.title = 'Tim''s Vermeer' and f.year = 2013 and f.director = 'Teller';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-lechera'), 1, '«Vermeer pintaba con una cámara oscura.» Se repite como un hecho y es una hipótesis — y con este cuadro tropieza. El conservador Walter Liedtke señalaba un agujero de alfiler hallado en el lienzo: la marca de un chinche del que colgar una cuerda encalada que, tensada como compás de carpintero, traza las líneas de fuga. Óptica de hilo y tiza, no de lentes. Y remataba: la luz dentro de una cámara oscura dura unos segundos; este cuadro costó meses. La hipótesis óptica sigue viva —Hockney, Steadman, Jenison—, pero «pintó con cámara» no es un hecho: es un debate.', 'myth', 'https://en.wikipedia.org/wiki/The_Milkmaid_(Vermeer)', 'Wikipedia, «Technique and materials»: entrevista a Liedtke (WNYC, 2009) citada allí');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-lechera'), 2, 'La cocina es la segunda versión de sí misma. Los rayos X revelan que Vermeer tapó dos cosas: un gran mapa mural tras el torso de la criada y una cesta de ropa bien visible junto a su falda roja —esta última dejó un leve cambio de tono (pentimento) en la pared, junto al calentador de pies, que aún se ve—. El cuadro gana con las restas: la pared vacía empuja toda la mirada hacia el hilo de leche.', 'fact', 'https://en.wikipedia.org/wiki/The_Milkmaid_(Vermeer)', 'Wikipedia, «Compositional strategy»: estudio técnico; página del Rijksmuseum y Essential Vermeer citados allí');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-lechera'), 3, 'En la ventana hay un cristal roto —y Vermeer pintó su reflejo. La grieta cruza el panel de la cuarta fila desde abajo, el último de la derecha, y se duplica sobre la madera del marco; otro vidrio está rayado con una línea blanca fina y otro aparece hundido hacia dentro. En la pared encalada: manchas, sombras, un clavo y su agujero. Nadie pinta «defectos» así por descuido: el desgaste es el realismo — una casa con humedades, no una fachada.', 'fact', 'https://en.wikipedia.org/wiki/The_Milkmaid_(Vermeer)', 'Wikipedia, «Technique and materials»: Serena Cant, Vermeer and His World (2009), citada allí');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-lechera'), 4, 'La inflación de la lechera, florín a florín —toda la escalada consta en los registros de subastas: 175 fl en 1696 (venta Dissius, Ámsterdam), 320 en 1701, 126 en 1719, 560 en 1765, 925 en 1768, 1.550 en 1798, 2.125 en 1813… y en 1908 el Rijksmuseum se la arrancó a los herederos Six: 550.000 florines por el lote de 39 cuadros, con el apoyo de la Vereniging Rembrandt. La criada que costó lo que una casa terminó valiendo un pedazo del presupuesto nacional.', 'fact', 'https://www.rijksmuseum.nl/en/collection/SK-A-2344', 'Rijksmuseum, ficha de la obra: cadena de provenance completa + «Acquisition: purchase 1908»');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-lechera'), 5, 'Se cuenta que esta cocina callada es en realidad un mensaje de amor. En la lectura emblemática neerlandesa, el calentador de pies del suelo era más que un brasero: bajo la falda calienta «todo el cuerpo por debajo de la cintura», y sus brasas podían significar «el calor de la lujuria en las tabernas o la pasión callada y verdadera de una esposa» (Cant). Tras él, un azulejo de Delft con un Cupido apenas visible; y hasta la leche tenía doble sentido —melken, en la jerga de la época, también era «seducir». ¿Virtud doméstica o coquetería a media luz? El cuadro se resiste: ella solo mira la leche.', 'legend', 'https://en.wikipedia.org/wiki/The_Milkmaid_(Vermeer)', 'Wikipedia, «Dutch iconography of maids»: Liedtke, Cant y catálogo del Met (2009) citados allí');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'la-lechera'), 'display', 'https://commons.wikimedia.org/wiki/File:Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.png', 'Rijksmuseum / Google Arts & Culture — Wikimedia Commons (dominio público)');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'la-lechera'), 'Única versión. Comprada en 1908 a los herederos del jonkheer Pieter Hendrik Six —550.000 fl por el lote de 39 cuadros— con apoyo de la Vereniging Rembrandt. Dataciones publicadas: c. 1657–58 (Met) / c. 1660 (ficha vigente del Rijksmuseum).', 'Rijksmuseum', 'Ámsterdam', 'Países Bajos');
commit;
-- end of story load: la-lechera (draft)
