-- Story load: La vocación de san Mateo (Caravaggio, Contarelli) (slug: la-vocacion-de-san-mateo) — draft state, pending Patrick's OK to publish
-- Pattern: autorretrato / girasoles loads (idempotent, accent-safe, docker cp + psql -f).
-- Deletes scoped per-artwork plus the one artist-level row this load owns (Caravaggio 1986 × Caravaggio).
-- Never artist_id-wide (see autorretrato header lesson).
-- Dating: 1599–1600 (Contarelli); Wikidata P571=1609 is a single-source error — never load 1609.
-- story_status: created -> draft (a promotion; publish is a separate, explicit step).
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'la-vocacion-de-san-mateo');
delete from film_connections where film_id = (select id from films where title = 'Caravaggio' and year = 1986) and artist_id = (select id from artists where slug = 'michelangelo-merisi-da-caravaggio');
delete from curiosities where artwork_id = (select id from artworks where slug = 'la-vocacion-de-san-mateo');
delete from image_assets where artwork_id = (select id from artworks where slug = 'la-vocacion-de-san-mateo');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'la-vocacion-de-san-mateo');
update artworks set summary = 'La vocación de san Mateo es un óleo sobre lienzo de más de tres metros (340 × 322 cm) que Caravaggio pintó entre 1599 y 1600 para la pared izquierda de la Capilla Contarelli, en San Luigi dei Francesi —la iglesia nacional de Francia en Roma, a dos pasos de Piazza Navona—, donde sigue colgando hoy, frente al Martirio de san Mateo y junto a la Inspiración del altar: el único gran ciclo de Caravaggio que puede verse aún en el sitio para el que se pintó. La escena es Mateo 9,9: Cristo entra desde la derecha con san Pedro, tiende la mano y un haz de luz cruza la estancia oscura hasta una mesa de recaudador de impuestos donde cinco hombres vestidos a la romana de 1600 —calzas, plumas, espadas— siguen contando monedas. En el centro, un barbaso señalándose el pecho con un gesto que cuatro siglos no han cerrado: «¿Yo?».', why_it_matters = 'Importa porque aquí nace el Barroco de una vez: un milagro contado como suceso de actualidad, con traje contemporáneo y luz lateral, y la gracia reducida a un instante —la mano tendida, el haz, la duda de Mateo— que el espectador completa. Era el primer gran encargo público y religioso de un pintor de fama callejera protegido por el cardenal Del Monte, y convirtió a Caravaggio, de la noche a la mañana, en el pintor más famoso de Roma. Y sigue en su capilla: para verla hay que plantarse donde se plantaron los peregrinos del Jubileo de 1600 —el cuadro no se visita, se peregrina.', essay = NULL, palette = '["#1B130C", "#6E4E2E", "#C9A96B", "#8C3B2A", "#3F4A35"]', story_status = 'draft', updated_at = now() where slug = 'la-vocacion-de-san-mateo';
insert into films (title, year, director) select 'Caravaggio', 1986, 'Derek Jarman' where not exists (select 1 from films where title = 'Caravaggio' and year = 1986 and director = 'Derek Jarman');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, null, (select id from artists where slug = 'michelangelo-merisi-da-caravaggio'), null, 'La gramática Contarelli: luz única lateral, cuerpos a media sombra y el anacronismo como método', 'Jarman rodó en un almacén en penumbra con Nigel Terry, Sean Bean y una debutante Tilda Swinton; el director de fotografía Gabriel Beristain advirtió que casi todos los cuadros de Caravaggio se iluminan desde la izquierda y los decorados se rediseñaron para que la luz entrara así —el cuadro convertido en plano de luz—. Y donde Caravaggio vestía el Evangelio con la Roma de 1600, Jarman responde con calculadoras, motos y luz eléctrica: el mismo anacronismo, otra centuria. Oso de Plata en Berlín y corto en el Turner Prize: cine pensado como pintura.', 'La escena-tipo del film es una mesa iluminada de refilón en un fondo que se traga todo: los cuerpos emergen a medias, las manos —que en Jarman casi siempre quieren decir deseo o muerte— quedan más lejos de la lámpara que los rostros. Es la lección de la capilla Contarelli vuelta cámara: un solo vector de luz que decide qué existe en el encuadre y qué queda en sombra, y una acción que se detiene justo antes del gesto decisivo, como el instante congelado de La vocación. Donde el cuadro hacía dudar a Mateo entre el dinero y la mano tendida, el film hace dudar a sus modelos entre el deseo y la violencia — la mesa de pronto, la luz de siempre.', 'none', NULL from films f where f.title = 'Caravaggio' and f.year = 1986 and f.director = 'Derek Jarman';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-vocacion-de-san-mateo'), 1, 'La leyenda negra dice que este cuadro escandalizó a la Iglesia y acabó rechazado. Falso: el contrato de las dos telas laterales se firmó el 23 de julio de 1599 y La vocación estaba instalada y cobrada en julio de 1600 —el encargo consagró a Caravaggio, no lo vetó—. Lo que sí rechazó la iglesia fue otra cosa: la estatua de mármol de Cobaert (un Mateo sin ángel) y, en 1602, la primera versión del retablo, San Mateo y el ángel, sustituida por la Inspiración que hoy se ve —aquella primera versión acabó destruida en la Segunda Guerra Mundial—. El escándalo fue vecino de capilla; La vocación fue un triunfo.', 'myth', 'https://en.wikipedia.org/wiki/Contarelli_Chapel', 'Wikipedia, «Contarelli Chapel»: contrato 23-7-1599, instalación julio 1600, rechazos de Cobaert y del retablo; el rechazo de San Mateo y el ángel (1602) se verifica en https://en.wikipedia.org/wiki/The_Inspiration_of_Saint_Matthew');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-vocacion-de-san-mateo'), 2, 'La mano de Cristo, tendida y lánguida, es la mano de Dios en la Creación de Adán de Miguel Ángel —pero invertida—: donde el Creador daba la vida al primer Adán, el «último Adán» (así llama Pablo a Cristo) se la da ahora a Levi el publicano. Guiño de taller o teología en acción: el pintor se llamaba Michelangelo Merisi y firmó con el nombre del maestro de la Sixtina el gesto más citado de su carrera.', 'fact', 'https://saintlouis-rome.net/horaires-visite-opening-hours/caravage/', 'Ficha oficial de la iglesia («Le Christ, dans le même geste qu''Adam dans la fresque de la création de Michel Ange»); doblemente verificado en Wikipedia (Calling), que cita a Lavin, 1993');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-vocacion-de-san-mateo'), 3, 'El cuadro nació contra el reloj del Jubileo: en 1599, con Roma esperando un diluvio de peregrinos franceses y la capilla vacía tras años de obras paradas, el cardenal Del Monte —prefecto de la Fábrica de San Pedro y patrón personal de Caravaggio— colocó a «su» pintor en el encargo. Hasta entonces Caravaggio no había pintado nunca a esa escala ni para un altar público: dos lienzos de tres metros, contratados en julio de 1599, listos en julio de 1600.', 'fact', 'https://en.wikipedia.org/wiki/Contarelli_Chapel', 'Wikipedia, «Contarelli Chapel» (contexto del Jubileo, intervención de Del Monte, fechas); la ficha de la iglesia lo llama «su primer gran encargo de temas religiosos»');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-vocacion-de-san-mateo'), 4, 'Ese rayo de luz que entra por la derecha no es decorado: en la capilla, cada uno de los dos lienzos laterales recibe la única luz natural de la estancia desde ese mismo lado, y Caravaggio pintó su haz de acuerdo con ella —la luz del cuadro prolonga la luz real de la capilla—. La oscuridad romana de la iglesia, que era un problema, quedó convertida en escenografía: el tenebrismo antes de llamarse tenebrismo.', 'fact', 'https://en.wikipedia.org/wiki/Contarelli_Chapel', 'Wikipedia, «Contarelli Chapel»: «each of the two side paintings are lit by a beam coming from the only source of natural light»');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'la-vocacion-de-san-mateo'), 5, 'Se cuenta que, cuatro siglos después, nadie sabe seguro quién es Mateo en el cuadro. El consenso señala al barbudo del centro, que se señala a sí mismo («¿yo?») —apoyado por las otras dos telas de la capilla, donde el mismo modelo barbudo hace de Mateo—. Pero desde 1988 una corriente académica defiende que el gesto es de asombro ajeno: el barbudo señala al joven agachado de la izquierda, que sigue contando monedas sin enterarse («¿él?»). El elegido sería entonces el único que aún no ha mirado: la vocación retratada un segundo antes de ser oída.', 'legend', 'https://en.wikipedia.org/wiki/The_Calling_of_Saint_Matthew', 'Wikipedia (Calling): consenso de Lavin (1993) frente a la hipótesis de Hass (1988); la ficha de la iglesia también recoge la duda sobre el personaje');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'la-vocacion-de-san-mateo'), 'display', 'https://commons.wikimedia.org/wiki/File:Caravaggio_—_The_Calling_of_Saint_Matthew.jpg', 'Fotografía: Gleb Simonov (CC0) — Wikimedia Commons (dominio público)');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'la-vocacion-de-san-mateo'), 'Primera fase del ciclo Contarelli: contrato 23-7-1599, instalado y pagado en julio de 1600, a tiempo para el Jubileo. Cuelga en su emplazamiento original, pared izquierda, frente al Martirio. Nota de datos: el P571=1609 de Wikidata es error de fuente única; datación universal del encargo: 1599–1600.', 'Cappella Contarelli, San Luigi dei Francesi', 'Roma', 'Italia');
commit;
-- end of story load: la-vocacion-de-san-mateo (draft)
