-- Story load: Las Meninas (Velázquez, Prado) (slug: las-meninas) — draft state, pending Patrick's OK to publish
-- Pattern: autorretrato / girasoles loads (idempotent, accent-safe, docker cp + psql -f).
-- Deletes scoped per-artwork plus the one artist-level row this load owns (Alatriste × Velázquez).
-- Never artist_id-wide (see autorretrato header lesson).
-- story_status: created -> draft (a promotion; publish is a separate, explicit step).
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'las-meninas');
delete from film_connections where film_id = (select id from films where title = 'Alatriste' and year = 2006) and artist_id = (select id from artists where slug = 'diego-velazquez');
delete from curiosities where artwork_id = (select id from artworks where slug = 'las-meninas');
delete from image_assets where artwork_id = (select id from artworks where slug = 'las-meninas');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'las-meninas');
update artworks set summary = 'Las Meninas —La familia de Felipe IV en los inventarios del XVIII— es un óleo sobre lienzo de gran formato (318 × 276 cm, figuras a tamaño natural) que Diego Velázquez pintó en 1656 en el taller que ocupaba en el Alcázar de Madrid: la pieza principal del llamado Cuarto del Príncipe, aposentos que habían sido del príncipe Baltasar Carlos, muerto una década antes. En el centro óptico, la infanta Margarita, cinco años; a su lado las meninas Isabel de Velasco y María Agustina Sarmiento —que le ofrece agua en un búcaro—, la enana Mari Bárbola y Nicolasito Pertusato, que molesta con el pie al mastín dormido; detrás, doña Marcela de Ulloa y el guardadamas; al fondo, a contraluz en la puerta, el aposentador de la reina José Nieto; a la izquierda, el propio Velázquez ante un gran lienzo de espaldas. Y en el espejo del fondo, los bustos de Felipe IV y Mariana de Austria: los reyes están fuera del cuadro, exactamente donde estamos nosotros. Pintado para el despacho del rey, ingresó en el Museo del Prado al fundarse, en 1819; ni viaja ni se presta: no sale de Madrid.', why_it_matters = 'Importa porque es un cuadro sobre el mirar: quién mira, a quién y desde dónde —el espectador ocupa el trono vacío del punto de vista real, y cinco de las nueve figuras lo miran a él. Es también la reivindicación suprema del oficio: pintado mientras Velázquez pleiteaba por el hábito de Santiago, eleva «el oficio manual de pintar» a arte liberal poniendo al pintor —por primera vez a esta escala— dentro del cuadro de la corte. Por eso ningún lienzo ha sido mirado tan de cerca durante tanto tiempo: Giordano lo llamó «teología de la pintura», Manet hizo de su autor «el pintor de los pintores», Foucault abrió con él Las palabras y las cosas y Picasso lo desarmó en 58 piezas.', essay = NULL, palette = '["#3A2E22", "#6E5B43", "#CBBFA8", "#44586E", "#9E2B20"]', story_status = 'draft', updated_at = now() where slug = 'las-meninas';
insert into films (title, year, director) select 'Alatriste', 2006, 'Agustín Díaz Yanes' where not exists (select 1 from films where title = 'Alatriste' and year = 2006 and director = 'Agustín Díaz Yanes');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, null, (select id from artists where slug = 'diego-velazquez'), null, 'Los cuadros de Velázquez como reloj del film', 'Wikipedia es documenta que «las obras pictóricas de Velázquez marcan la progresión temporal» de la película: El aguador de Sevilla aparece recién adquirido y luego ya colgado en Palacio, y la secuencia del sitio de Breda «empalma con el cuadro homónimo» —La rendición de Breda— antes de que el propio Íñigo lo critique en voz en off. Alatriste camina por una España vestida y calzada por Velázquez: la corte de Felipe IV, los tercios, el negro y el ocre.', 'La batalla de Breda se resuelve como un cuadro vivo de Las lanzas: polvo dorado, horizonte bajo, haces de picas verticales cruzando el encuadre en diagonales suaves, cámara a ras del suelo y los tercios a contraluz — mirada de Velázquez: la luz llega de un lado único y alto, el negro se come media composición y la jerarquía la marca quién recibe esa luz, exactamente como en el taller de Las Meninas la infanta es la única plenamente iluminada. En los interiores palaciegos, la lección se repite en clave de palacio: ventanas altas laterales, penumbra creciente hacia el fondo, siluetas cortadas contra puertas abiertas — el cuadro del taller convertido en gramática de fotografía (Paco Femenía) más que en cita puntual.', 'none', NULL from films f where f.title = 'Alatriste' and f.year = 2006 and f.director = 'Agustín Díaz Yanes';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-meninas'), 1, '«Es el retrato de la infanta Margarita»: falso — es el retrato de un taller entero. Ni siquiera se llamó así: en el inventario de 1666 del Alcázar figuraba como «una pintura de quattro baras y media de alto y tres y media de ancho… retratando a la señora emperatriz con sus damas y una enana de mano de Diego belázquez» —Margarita, prometida como emperatriz, con sus meninas y Mari Bárbola—. Tras el incendio de 1734 se llamó «La familia de Felipe IV» (nombre con el que ingresó en el Prado en 1819), y solo en 1843, en el catálogo de Pedro de Madrazo, estrenó el título actual, tomado de Palomino: «dos damitas acompañan a la infanta niña; son dos meninas». O sea: el nombre que ganó la historia nombra a las figuras secundarias, y la «niña retratada» es un mito doble — el sujeto del cuadro es la propia pintura, un taller real cazado en el instante de trabajar.', 'myth', 'https://es.wikipedia.org/wiki/Las_meninas', 'Wikipedia es (artículo destacado), secciones «El título» e «Historia del cuadro»: cita textual del inventario de 1666 y datación del nombre de 1843');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-meninas'), 2, 'En la pared del fondo, un rectángulo pálido flotando en la penumbra: el espejo que devuelve los bustos de Felipe IV y Mariana de Austria. Es el único doble retrato conocido de los reyes pintado por Velázquez, y su truco más profundo: nos coloca de pie donde estaban ellos, mirando lo que ellos miraban. La lectura tradicional —la de Palomino— es que el espejo muestra justo lo que Velázquez pintaba (el retrato de los monarcas) mientras su hija entraba al taller; pero Janson y Snyder propusieron la inversa: que el reflejo no es de los reyes sino del lienzo que vemos de espaldas, donde ya estarían retratados. Nadie ha cerrado la cuestión. Michel Foucault abrió Les Mots et les Choses (1966) con este cuadro: la representación clásica representándose a sí misma.', 'fact', 'https://en.wikipedia.org/wiki/Las_Meninas', 'Wikipedia en (featured article), secciones «Mirror and reflection» e «Influence»; la cita de Gaggi («único doble retrato conocido») y la lectura de Snyder/Janson');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-meninas'), 3, 'Los rayos X del Prado (estudio técnico de Carmen Garrido) muestran un cuadro menos sereno de lo que parece: lienzo cosido de tres bandas de tela, pintado sin dibujo previo, a manchas de color «a la manera veneciana», y sembrado de arrepentimientos — la cabeza de Velázquez miraba primero hacia la infanta; la mano derecha de la niña estaba más alta; en el espejo, el rey tiene un encaje abocetado con pigmentos más densos que la reina, «casi invisible». El borde izquierdo fue recortado en una reentelada temprana («se perdió muy poco trozo de la orilla»). Y en el incendio del Alcázar de 1734, rescatado a toda prisa como otras obras que volaron por las ventanas, la mejilla izquierda de la infanta quedó dañada y hubo de ser casi íntegramente repintada por el pintor real Juan García de Miranda.', 'fact', 'https://es.wikipedia.org/wiki/Las_meninas', 'Wikipedia es, secciones «Técnica» (Garrido, radiografías, tres bandas, recorte) e «Historia del cuadro» (incendio de 1734, García de Miranda)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-meninas'), 4, 'Tres siglos de pintores peregrinando ante el mismo enigma: Luca Giordano, admitido a verlo en los apartamentos privados del rey, lo llamó «la teología de la pintura». En 1865 Manet, recién salido del Prado, le escribió a Fantin-Latour: «Velázquez por sí solo justifica el viaje. Los pintores de todas las escuelas que le rodean, en el museo de Madrid, parecen simples aprendices. Es el pintor de los pintores». Y el 17 de agosto de 1957 Picasso se encerró en Cannes con una reproducción y no salió hasta el 30 de diciembre: 58 interpretaciones —la primera en grises puros, con un Velázquez gigante cuya cabeza toca el techo y la cruz de Santiago agrandada al pecho— que hoy llenan una sala entera del Museu Picasso de Barcelona.', 'fact', 'https://es.wikipedia.org/wiki/Las_meninas', 'Wikipedia es, secciones «Opiniones» (Giordano, carta de Manet a Fantin-Latour) e «Influencia» (Picasso: fechas, Cannes, detalle de la primera versión); en.wiki «Influence» confirma las 58 y el Museu Picasso');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-meninas'), 5, 'Sobre el pecho del autorretrato brilla la cruz roja de la Orden de Santiago — imposible en 1656: Velázquez no fue investido caballero hasta 1659, tres años después de acabar el cuadro, y murió en agosto de 1660, enterrado con el vestido y la insignia que tanto deseó. La cruz, pues, se pintó después. Se cuenta —sin ninguna certeza oficial— que fue Felipe IV quien mandó añadirla a la muerte del pintor; y Palomino fue más lejos todavía: «algunos dicen que su Majestad mismo se lo pintó, para aliento de los Profesores de esta Nobilísima Arte». Un rey tomando el pincel para ennoblecer a su pintor muerto: la leyenda más hermosa que guarda este cuadro.', 'legend', 'https://es.wikipedia.org/wiki/Las_meninas', 'Wikipedia es, «Contexto» (entierro, «se dice, sin tener ninguna certeza oficial») y «Personajes» nº 9 (cita de Palomino); en.wiki «Subjects» confirma 1659 y la orden póstuma del rey según Palomino');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'las-meninas'), 'display', 'https://commons.wikimedia.org/wiki/File:Las_Meninas,_by_Diego_Vel%C3%A1zquez,_from_Prado_in_Google_Earth.jpg', 'Museo del Prado (Prado in Google Earth) — Wikimedia Commons (dominio público)');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'las-meninas'), 'Pintado para el despacho del rey en el cuarto de verano del Alcázar de Madrid; la escena representa la pieza principal del Cuarto del Príncipe (antiguos aposentos de Baltasar Carlos), taller de Velázquez. Por tamaño e importancia no se presta a exposiciones.', 'Museo del Prado', 'Madrid', 'España');
commit;
-- end of story load: las-meninas (draft)
