-- Story load: Las dos Fridas (Kahlo, MAM CDMX) (slug: las-dos-fridas) — draft state, pending Patrick's OK to publish
-- Pattern: autorretrato / girasoles loads (idempotent, accent-safe, docker cp + psql -f).
-- RIGHTS (ADR-0003, Patrick's decision 2026-10-06): Kahlo died 1954 — the work is NOT public domain.
-- This load sets rights_status = 'blocked' and inserts ZERO image_assets (story-only model).
-- Deletes scoped per-artwork. One obra-level connection (Frida 2002, Julie Taymor).
-- story_status: created -> draft (a promotion; publish is a separate, explicit step).
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'las-dos-fridas');
delete from curiosities where artwork_id = (select id from artworks where slug = 'las-dos-fridas');
delete from image_assets where artwork_id = (select id from artworks where slug = 'las-dos-fridas');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'las-dos-fridas');
update artworks set summary = 'Las dos Fridas es un óleo sobre lienzo de gran formato (173,5 × 173 cm) que Frida Kahlo pintó en 1939, el año en que se formalizó su divorcio de Diego Rivera (noviembre de 1939). Es un doble autorretrato: dos Fridas sentadas juntas de la mano en una banca forrada de verde, bajo un cielo grisáceo de tormenta. Una viste un traje de tehuana —la Frida mexicana, la que Diego amaba— y guarda en el regazo un retrato en miniatura de Diego niño; la otra lleva un vestido victoriano de encaje blanco —la Frida europea, la rechazada— y sujeta las tijeras quirúrgicas con que se ha cortado la vena que las une: la sangre gotea sobre el encaje. Fue la primera obra de gran formato de Kahlo y desde 1966 cuelga en el Museo de Arte Moderno de Ciudad de México, que la recibió tras la compra del INBA en 1947.', why_it_matters = 'Importa porque aquí Kahlo pinta el desamor como una lección de anatomía: dos corazones al descubierto —copiados de libros de anatomía—, una vena que los une y unas tijeras que la seccionan; el cuerpo convertido en biografía. Es además su primera obra de gran formato, pintada justo cuando decidió ganarse la vida con su pintura tras la ruptura, y la prueba de su tesis: «nunca pinté mis sueños, pinté mi propia realidad» — nada aquí es sueño; todo es carne, memoria y facturación del dolor. Y es su doble identidad —lo europeo y lo mexicano— resuelta en un solo gesto: dos mujeres que no son más que una, tomadas de la mano.', essay = NULL, palette = '["#EFEAE0", "#A6ACA9", "#46594A", "#8E3030", "#C13A31"]', rights_status = 'blocked', story_status = 'draft', updated_at = now() where slug = 'las-dos-fridas';
insert into films (title, year, director) select 'Frida', 2002, 'Julie Taymor' where not exists (select 1 from films where title = 'Frida' and year = 2002 and director = 'Julie Taymor');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, (select id from artworks where slug = 'las-dos-fridas'), null, null, 'La disolución del cuadro en cuerpo: el doble autorretrato como gramática del montaje', 'La película abre secuencias enteras como tomas de cuadros reales de Kahlo que se disuelven en acción viva con actores — y Las dos Fridas (1939) está explícitamente entre las obras «mostradas directamente o recreadas por los personajes», junto a Frieda y Diego Rivera, Lo que me dio el agua, La columna rota y El venado herido. Taymor convierte el recurso del doble autorretrato —una mujer, dos identidades— en la ley del film: Hayek se divide y se multiplica en vestimentas, espejos y escenarios.', 'Donde Kahlo resuelve la dualidad en simetría frontal —dos figuras sentadas en el eje, cielo de tormenta plano detrás, la vena como línea de montaje entre ambos corazones—, Taymor toma el mismo diagrama y lo pone a correr: la cámara arranca en la superficie pintada, frontal y quieta como el cuadro, y disuelve hacia los actores, de modo que el film entero funciona como ese pasaje del lienzo al cuerpo. La doble Frida se vuelve régimen de vestuario y de luz: el blanco de encaje europeo de las secuencias de Nueva York y París contra los saturados del traje tehuano en México; y la vena cortada se traduce en la puesta en escena del cuerpo herido —corsés, vendas, la cama convertida en caballete— que el film hereda de la lección de anatomía del cuadro. La tormenta gris del fondo es, en el film, iluminación: los interiores del divorcio pierden saturación hasta casi el gris del cielo del cuadro. Curiosidad de producción que cierra el círculo: el proyecto rival que casi le roba la película se titulaba precisamente The Two Fridas.', 'none', NULL from films f where f.title = 'Frida' and f.year = 2002 and f.director = 'Julie Taymor';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-dos-fridas'), 1, 'El mito de «Frida la surrealista» no nació de ella: se lo colgó André Breton, que la reclamó para su movimiento y describió su obra como «una cinta alrededor de una bomba». Ella lo destapó de su propia voz: «Creían que yo era surrealista, pero no lo era. Nunca pinté mis sueños. Pinté mi propia realidad». Llegó a declarar que detestaba el surrealismo —«arte burgués»—, no «el arte verdadero que el pueblo espera del artista». La ironía perfecta: este cuadro, autobiografía en estado puro (divorcio, corazones, sangre), colgó en enero de 1940 en la Exposición Internacional Surrealista de la Ciudad de México, junto a La mesa herida. El etiquetado era marketing de Breton; la mercancía nunca fue suya.', 'myth', 'https://es.wikipedia.org/wiki/Frida_Kahlo', 'Biografía de Kahlo, secciones 1938–1940: cita textual «Creían que yo era surrealista…»; Breton y «cinta alrededor de una bomba» también en la bio EN (Helland 1990–91 para el «detestaba»); la muestra de 1940 verificada en la ficha de la obra (EN)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-dos-fridas'), 2, 'Es una clase de anatomía: los dos corazones están a la vista, «copiados de libros de anatomía». A la izquierda, la Frida europea —vestido victoriano de encaje blanco, la que Diego ya no amaba— sujeta las tijeras quirúrgicas con que se ha cortado la arteria; la sangre salpica el encaje y corre el peligro de desangrarse. A la derecha, la Frida de tehuana —la favorita de Diego— sostiene en el regazo un retrato en miniatura de Diego niño, colgado de la propia vena como un amuleto: la arteria que sale del corazón mexicano termina en su retrato. La vena que une a las dos pasa por sus manos: cortarla es, literalmente, dejar de estar unidas.', 'fact', 'https://es.wikipedia.org/wiki/Las_dos_Fridas', 'Artículo de la obra: vestimentas, arteria, miniatura de Diego, tijeras, corazones de libro de anatomía; «pinza hemostática» según la ficha FR y EN («forceps») — misma lectura');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-dos-fridas'), 3, 'Es su primera obra de gran formato: 173,5 × 173 cm. Hasta entonces Kahlo pintaba formatos íntimos —láminas de metal, pequeños autorretratos—, y tras la separación pasó deliberadamente al lienzo grande porque «eran más fáciles de exponer»: decidida a vivir de su arte, hizo del dolor su obra más ambiciosa. El calendario lo dice todo: el divorcio se formalizó en noviembre de 1939 y ella ya había vuelto de Nueva York y París ese mismo año, sola y en plena fiebre productiva. PBS lo resume: pintada «en el momento de su divorcio de Diego», la primera gran escala de Frida.', 'fact', 'https://www.pbs.org/weta/fridakahlo/worksofart/index.html', 'PBS/WETA, «Works of Art: The Two Fridas» (colección MAM; «first large-scale work painted by Frida»); dimensión exacta 173,5 × 173 cm según ficha EN/ES de la obra; contexto de formatos y fecha de divorcio según la biografía EN de Kahlo');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-dos-fridas'), 4, 'El cuadro se quedó con Frida ocho años: lo compró el Instituto Nacional de Bellas Artes en 1947 —el pago más alto que recibió por un cuadro en vida, según se documenta: 4.000 pesos, más 36 por el marco—, y el INBA lo trasladó al Museo de Arte Moderno el 28 de diciembre de 1966. Venía de ganar el Premio Nacional (1946, por Moisés), el año en que su economía por fin mejoró. Y no era una compra cualquiera: aquellas adquisiciones de la Sala de arte del INBAL son el acta de nacimiento de la colección del MAM — este cuadro es piedra fundacional del museo.', 'fact', 'https://en.wikipedia.org/wiki/The_Two_Fridas', 'Ficha de la obra: INBA 1947, traslado al MAM 28-12-1966; Premio Nacional 1946 según la biografía EN de Kahlo; el precio (4.000 + 36 pesos) verificado también en fridakahlo.org y fr.wikipedia (fuentes secundarias, ojo de Patrick); la página oficial del acervo del MAM confirma la compra origen de la colección');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'las-dos-fridas'), 5, 'Se cuenta que las dos Fridas son sus dos sangres: la alemana del padre —el fotógrafo Guillermo Kahlo— y la mexicana de la madre —Matilde Calderón, mestiza—; la lectura popular quiere el cuadro como acta de identidad dual, Europa y México tomados de la mano. Historiadores del arte lo sugieren; la propia Frida contó otra cosa: que la imagen nació del recuerdo de una amiga imaginaria de su infancia, y después admitió que expresaba su desesperación y soledad tras la separación. Dos leyendas sobre el mismo lienzo —la de las dos sangres y la de la amiga invisible— y, en el centro, una sola mujer sosteniéndose la mano.', 'legend', 'https://en.wikipedia.org/wiki/The_Two_Fridas', 'Ficha de la obra: lectura de herencia dual (padre alemán / madre mexicana) atribuida a historiadores; recuerdo de la «amiga imaginaria de la infancia» según Herrera, Frida Kahlo: The Paintings (1991), p. 135; versión del diario también en fridakahlo.org');
-- NO image_assets insert: ADR-0003 story-only (rights_status = 'blocked', Kahlo d. 1954)
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'las-dos-fridas'), 'Comprada por el INBA en 1947 (4.000 pesos + 36 por el marco, fuentes secundarias); trasladada al Museo de Arte Moderno el 28 de diciembre de 1966.', 'Museo de Arte Moderno (INBAL)', 'Ciudad de México', 'México');
commit;
-- end of story load: las-dos-fridas (draft)
