-- Recovery load: La noche estrellada (slug: noche-estrellada)
-- Generated from the live DB on 2026-10-03, before a supabase db reset.
-- Idempotent: targeted deletes + not-exists guards; never demotes story_status.
-- Load via docker cp + psql -f -- never pipe UTF-8 SQL through PowerShell.
begin;
delete from film_connections where artwork_id = (select id from artworks where slug = 'noche-estrellada') or artist_id = (select id from artists where slug = 'vincent-van-gogh');
delete from curiosities where artwork_id = (select id from artworks where slug = 'noche-estrellada');
delete from image_assets where artwork_id = (select id from artworks where slug = 'noche-estrellada');
delete from physical_instances where artwork_id = (select id from artworks where slug = 'noche-estrellada');
update artworks set rights_status = 'clear', story_status = 'published', summary = 'La noche estrellada es un óleo sobre lienzo (73,7 × 92,1 cm) que Vincent van Gogh pintó en junio de 1889 en el asilo de Saint-Paul-de-Mausole, en Saint-Rémy-de-Provence, donde se había internado voluntariamente tras la crisis de la oreja. Parte de la vista real de su ventana —las montañas de los Alpilles, el trigo amurallado— y añade lo que no estaba: un pueblo inventado, un campanario más holandés que provenzal y un cielo que ya no copia nada. Desde 1941 vive en el MoMA de Nueva York, adquirido mediante el legado de Lillie P. Bliss, y es hoy una de las imágenes más reconocibles del arte occidental.', why_it_matters = 'Importa porque aquí la noche deja de ser motivo y se convierte en estado interior: pintada de día y de memoria, la escena no documenta el cielo de Saint-Rémy sino lo que ese cielo le hacía a Vincent. Sus remolinos de impasto —azul ultramar y amarillos girando alrededor de cada estrella— convirtieron el ánimo en el verdadero tema del cuadro, y abrieron el camino del postimpresionismo al expresionismo. Y que su propio autor la declarara fracaso, y hoy sea icono universal, es el mejor recordatorio de que la historia del arte la escriben los que ven.', essay = NULL, palette = '["#122C4F", "#2A5D8F", "#F7D774", "#163832", "#EFE3B8"]', source_transcript = NULL, episode_youtube_id = NULL, wikidata_id = 'Q45585', met_object_id = NULL, published_at = '2026-10-03 04:01:29.191443+00', updated_at = now() where slug = 'noche-estrellada';
insert into films (title, year, director) select 'Lust for Life', 1956, 'Vincente Minnelli' where not exists (select 1 from films where title = 'Lust for Life' and year = 1956 and director = 'Vincente Minnelli');
insert into films (title, year, director) select 'Loving Vincent', 2017, 'Dorota Kobiela y Hugh Welchman' where not exists (select 1 from films where title = 'Loving Vincent' and year = 2017 and director = 'Dorota Kobiela y Hugh Welchman');
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, null, (select id from artists where slug = 'vincent-van-gogh'), null, 'La paleta y el lienzo como dispositivo dramático', 'MGM reprodujo 200 cuadros de Vincent ampliados a color e insertó copias pintadas por Robert Parker; las escenas se construyen para desembocar en los lienzos. La crítica del New York Times celebró en 1956 que «el flujo del color» fuera el principal dispositivo narrativo del film.', 'El film de Minnelli no imita la pincelada: la cita. Los planos se tiñen progresivamente con la paleta del cuadro que va a aparecer —ocre de Nuenen, amarillos de Arles, azules de Saint-Rémy— hasta que la composición del fotograma coincide con la del lienzo y el montaje funde pintura y acción. El mecanismo es pura gramática del color: la emoción no la interpreta el actor, la porta el pigmento.', 'none', NULL from films f where f.title = 'Lust for Life' and f.year = 1956 and f.director = 'Vincente Minnelli';
insert into film_connections (film_id, artwork_id, artist_id, movement_id, what_it_borrowed, mechanism, frame_analysis_text, evidence_visual, evidence_url) select f.id, (select id from artworks where slug = 'noche-estrellada'), null, null, 'El cielo en remolino y la pincelada cargada como gramática narrativa', 'Primer largometraje de la historia pintado fotograma a fotograma al óleo: 65.000 cuadros ejecutados por 125 pintores con la técnica de Van Gogh. Los cielos nocturnos de las transiciones reaniman literalmente los vórtices de La noche estrellada.', 'En los cielos de la película, cada astro es un núcleo de luz rodeado de anillos concéntricos de impasto que parecen girar sobre sí mismos. La composición reserva la proporción del cuadro —tres cuartos de cielo arriba, pueblo y ciprés comprimidos abajo— y la cámara deriva lateralmente como si se deslizara sobre la superficie pintada. La luz no viene de un foco: son las masas amarillas de estrellas y luna las que irradian, y el remolino central tira del ojo en horizontal, igual que en el lienzo de 1889. Es la misma geometría, ahora a 24 cuadros por segundo.', 'none', NULL from films f where f.title = 'Loving Vincent' and f.year = 2017 and f.director = 'Dorota Kobiela y Hugh Welchman';
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'noche-estrellada'), 1, 'Se dice que Van Gogh salió de noche a pintar el cielo tal cual lo veía desde su ventana. Falso: la pintó de día, en varias sesiones, en el taller de la planta baja del asilo. El pueblo no se veía desde su ventana —lo reconstruyó a partir de otros apuntes— y el campanario se parece más a los de su Holanda natal que a ninguno de Provenza. Hasta el ciprés está más cerca de lo que estaba en la realidad.', 'myth', 'https://www.moma.org/collection/works/79802', 'MoMA, ficha de la obra (excerpt de MoMA Highlights, 2019)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'noche-estrellada'), 2, 'La estrella más brillante del cuadro no es una estrella: es Venus. «Esta mañana vi el campo desde mi ventana mucho antes del amanecer, sin más luz que la estrella de la mañana, que parecía muy grande», le escribió a Theo. Los astrónomos confirman que Venus brillaba en la Provenza de junio de 1889 casi al máximo posible.', 'fact', 'https://vangoghletters.org/vg/letters/let777/letter.html', 'Carta 777 a Theo (c. 31 mayo–6 junio 1889); la nota 4 de la edición identifica Venus');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'noche-estrellada'), 3, 'Vincent la dio por perdida. Cuando envió el lote a Theo, retuvo La noche estrellada para ahorrar franqueo, y en su lista de lo «un poco bueno» no aparecía: «lo demás no me dice nada». A Émile Bernard le confesó que se había dejado llevar «hacia estrellas demasiado grandes — otro fracaso».', 'fact', 'https://en.wikipedia.org/wiki/The_Starry_Night', 'Síntesis de las cartas 805, 806 y 822 (Van Gogh Letters Project)');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'noche-estrellada'), 4, 'La luna está mal — astronómicamente hablando. Aquel junio de 1889 la luna estaba en fase gibosa menguante, pero Vincent pintó un creciente envuelto en un halo enorme. Los estudiosos del cielo de Van Gogh llevan décadas explicando por qué esa licencia es precisamente el punto.', 'fact', 'https://en.wikipedia.org/wiki/The_Starry_Night', 'Boime (1984) y Whitney (1986), citados ahí');
insert into curiosities (artwork_id, position, text, type, source_url, source_note) values ((select id from artworks where slug = 'noche-estrellada'), 5, 'Se cuenta que el ciprés es un puente: árbol de cementerio y de luto en el Mediterráneo, une la tierra con un cielo que Vincent pensaba como destino. Él mismo escribió: «Así como tomamos el tren para ir a Tarascón o Ruán, tomamos la muerte para ir a una estrella».', 'legend', 'https://www.moma.org/collection/works/79802', 'MoMA, ensayo «Observation and Imagination in The Starry Night»');
insert into image_assets (artwork_id, kind, source_url, credit) values ((select id from artworks where slug = 'noche-estrellada'), 'display', 'https://commons.wikimedia.org/wiki/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg', 'Google Art Project — Wikimedia Commons (dominio público)');
insert into physical_instances (artwork_id, version_note, location, city, country) values ((select id from artworks where slug = 'noche-estrellada'), NULL, 'Museum of Modern Art (MoMA)', 'Nueva York', 'Estados Unidos');
commit;
-- end of recovery load
